### ISSUE TITLE
Consider switching to poetry

### ISSUE THREAD

**Issue by harens** [sentimentinvestor/sentipy#4]
There are a variety of reasons why switching to [poetry](https://python-poetry.org) would be beneficial ([example](https://nanthony007.medium.com/stop-using-pip-use-poetry-instead-db7164f4fc72)), especially at this early stage of the project.  Most notably, it allows us to remove the current overcomplicated `setup.py/pyproject.toml/requirements.txt` setup.

I'd be happy to open a PR for this if the project maintainers feel it would be beneficial. Thanks.

<details>
<summary>Rough pyproject.toml</summary>
<br>

```toml
[tool.poetry]
name = "sentiment-investor"
version = "2.0.0"
description = "Access the Sentiment Investor API through Python"
authors = ["Robert Stok <rs.stok@gmail.com>"]
readme = "README.md"
license = "MIT"

homepage = "https://sentimentinvestor.com/"
repository = "https://github.com/sentimentinvestor/sentipy"
documentation = "https://docs.sentimentinvestor.com/python/"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sentimentinvestor/sentipy/issues"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
websocket-client = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
</details>
